name: Release process
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install snyk-iac-rules
        run: npm i -g snyk-iac-rules
      - name: Run the tests
        run: |
         snyk-iac-rules test 
      - name: Build the bundle
        run: |
          snyk-iac-rules build
      - name: Bump version
        uses: remorses/bump-version@js
        with:
          version_file: ./VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Version
        id: version
        run: |
          echo ::set-output name=version_tag::$(cat ./VERSION)
      - name: Push changes to master 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
        env:
          DEFAULT_BUMP: patch
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.OCI_REGISTRY_USERNAME }}
          password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
      - name: Tag & Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.version_tag }}
          prerelease: false
          files: |
            bundle.tar.gz
      - name: Publish rules
        run: snyk-iac-rules push --registry $OCI_REGISTRY_URL bundle.tar.gz
        env:
          OCI_REGISTRY_URL: "docker.io/benlaplanche/iac-custom-rules:${{ steps.version.outputs.version_tag }}"
      - name: Update Snyk
        run: |
          curl --location --request PATCH 'https://api.snyk.io/v3/groups/ea961b5f-6acd-46ef-b209-fcffc6930ef1/settings/iac/?version=2021-11-03~beta' \
          --header 'Content-Type: application/vnd.api+json' \
          --header 'Authorization: token ${{ secrets.SNYK_TOKEN }}' \
          --data-raw '{
            "data": {
                  "type": "iac_settings",
                  "attributes": {
                    "custom_rules": {
                      "oci_registry_url": "https://registry-1.docker.io/benlaplanche/iac-custom-rules",
                      "oci_registry_tag": "${{ steps.version.outputs.version_tag }}",
                      "is_enabled": true
                    }
                }
            }
          }'
