name: Build & Test Custom Rules 
on: [push]
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install snyk-iac-rules
        run: npm i -g snyk-iac-rules
      - name: Run the tests
        run: |
         snyk-iac-rules test 
      - name: Build the bundle
        run: |
          snyk-iac-rules build
      - name: Run integration tests with Snyk IaC CLI
        continue-on-error: true #Setting this as we're only looking to validate that our rule correctly appeared in the results
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
          args: --rules=bundle.tar.gz --org=ben.laplanche --json-file-output=results.json
      - name: Validate the Snyk IaC results
        run: |
          wget https://github.com/shellspec/shellspec/releases/latest/download/shellspec-dist.tar.gz
          tar zxvf shellspec-dist.tar.gz
          ln -s shellspec/shellspec /bin/shellspec
          cd integration
          shellspec
        shell: bash
